//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelERP {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelERP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Ajustes {
            get {
                return ResourceManager.GetString("Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo trabajo.
        /// </summary>
        public static string AñadirNuevoTrabajo {
            get {
                return ResourceManager.GetString("AñadirNuevoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo servicio.
        /// </summary>
        public static string AñadirServicio {
            get {
                return ResourceManager.GetString("AñadirServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir servicio al usuario.
        /// </summary>
        public static string AñadirServsuario {
            get {
                return ResourceManager.GetString("AñadirServsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo trabajo.
        /// </summary>
        public static string AñadirTraUsuario {
            get {
                return ResourceManager.GetString("AñadirTraUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo usuario.
        /// </summary>
        public static string AñadirUsuario {
            get {
                return ResourceManager.GetString("AñadirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos: .
        /// </summary>
        public static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar turno.
        /// </summary>
        public static string BorrarTurno {
            get {
                return ResourceManager.GetString("BorrarTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF: .
        /// </summary>
        public static string Cif {
            get {
                return ResourceManager.GetString("Cif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo: .
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectar Telegram.
        /// </summary>
        public static string ConectarTelegram {
            get {
                return ResourceManager.GetString("ConectarTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar servicio.
        /// </summary>
        public static string DelServicio {
            get {
                return ResourceManager.GetString("DelServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar trabajo.
        /// </summary>
        public static string DelTrabajo {
            get {
                return ResourceManager.GetString("DelTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar usuario.
        /// </summary>
        public static string DelUsuario {
            get {
                return ResourceManager.GetString("DelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion: .
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deuda: .
        /// </summary>
        public static string Deuda {
            get {
                return ResourceManager.GetString("Deuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deudas.
        /// </summary>
        public static string Deudas {
            get {
                return ResourceManager.GetString("Deudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias: .
        /// </summary>
        public static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion: .
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo.
        /// </summary>
        public static string Domingo {
            get {
                return ResourceManager.GetString("Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D.
        /// </summary>
        public static string DomingoCorto {
            get {
                return ResourceManager.GetString("DomingoCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email: .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar codigo.
        /// </summary>
        public static string EnviarCod {
            get {
                return ResourceManager.GetString("EnviarCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar factura.
        /// </summary>
        public static string EnviarFact {
            get {
                return ResourceManager.GetString("EnviarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar mensaje.
        /// </summary>
        public static string EnviarMsg {
            get {
                return ResourceManager.GetString("EnviarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar nota.
        /// </summary>
        public static string EnviarNot {
            get {
                return ResourceManager.GetString("EnviarNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba aqui el mensaje que quiere enviar.
        /// </summary>
        public static string EscribirMensaje {
            get {
                return ResourceManager.GetString("EscribirMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura .
        /// </summary>
        public static string Factura {
            get {
                return ResourceManager.GetString("Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        public static string Facturas {
            get {
                return ResourceManager.GetString("Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar solo facturas sin pagar.
        /// </summary>
        public static string FacturasNoPagadas {
            get {
                return ResourceManager.GetString("FacturasNoPagadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha: .
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha limite: .
        /// </summary>
        public static string FechaLimite {
            get {
                return ResourceManager.GetString("FechaLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frances.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string HeaderAño {
            get {
                return ResourceManager.GetString("HeaderAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string HeaderApellidos {
            get {
                return ResourceManager.GetString("HeaderApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string HeaderEmail {
            get {
                return ResourceManager.GetString("HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string HeaderFecha {
            get {
                return ResourceManager.GetString("HeaderFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string HeaderFin {
            get {
                return ResourceManager.GetString("HeaderFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string HeaderID {
            get {
                return ResourceManager.GetString("HeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string HeaderInicio {
            get {
                return ResourceManager.GetString("HeaderInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string HeaderMes {
            get {
                return ResourceManager.GetString("HeaderMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string HeaderNombre {
            get {
                return ResourceManager.GetString("HeaderNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string HeaderPrecio {
            get {
                return ResourceManager.GetString("HeaderPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string HeaderReferencia {
            get {
                return ResourceManager.GetString("HeaderReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string HeaderSeleccionar {
            get {
                return ResourceManager.GetString("HeaderSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string HeaderServicios {
            get {
                return ResourceManager.GetString("HeaderServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string HeaderTelefono {
            get {
                return ResourceManager.GetString("HeaderTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        public static string HeaderTotal {
            get {
                return ResourceManager.GetString("HeaderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos.
        /// </summary>
        public static string HeaderTrabajos {
            get {
                return ResourceManager.GetString("HeaderTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string HeaderUsuario {
            get {
                return ResourceManager.GetString("HeaderUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba los apellidos aqui.
        /// </summary>
        public static string HintApellido {
            get {
                return ResourceManager.GetString("HintApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba aqui para buscar.
        /// </summary>
        public static string HintBuscar {
            get {
                return ResourceManager.GetString("HintBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca aqui la descripcion del servicio.
        /// </summary>
        public static string HintDescripcion {
            get {
                return ResourceManager.GetString("HintDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca aqui la descripcion del trabajo.
        /// </summary>
        public static string HintDescripcionTrabajo {
            get {
                return ResourceManager.GetString("HintDescripcionTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el email aqui.
        /// </summary>
        public static string HintEmail {
            get {
                return ResourceManager.GetString("HintEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el nombre aqui.
        /// </summary>
        public static string HintNombre {
            get {
                return ResourceManager.GetString("HintNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el precio.
        /// </summary>
        public static string HintPrecio {
            get {
                return ResourceManager.GetString("HintPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el numero telefono aqui.
        /// </summary>
        public static string HintTelefono {
            get {
                return ResourceManager.GetString("HintTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion de la empresa.
        /// </summary>
        public static string InfoEmpresa {
            get {
                return ResourceManager.GetString("InfoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves.
        /// </summary>
        public static string Jueves {
            get {
                return ResourceManager.GetString("Jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a J.
        /// </summary>
        public static string JuevesCorto {
            get {
                return ResourceManager.GetString("JuevesCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes.
        /// </summary>
        public static string Lunes {
            get {
                return ResourceManager.GetString("Lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L.
        /// </summary>
        public static string LunesCorto {
            get {
                return ResourceManager.GetString("LunesCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar pagada.
        /// </summary>
        public static string MarcarPagado {
            get {
                return ResourceManager.GetString("MarcarPagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes.
        /// </summary>
        public static string Martes {
            get {
                return ResourceManager.GetString("Martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        public static string MartesCorto {
            get {
                return ResourceManager.GetString("MartesCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje enviado con exito.
        /// </summary>
        public static string MensajeEnviado {
            get {
                return ResourceManager.GetString("MensajeEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miercoles.
        /// </summary>
        public static string Miercoles {
            get {
                return ResourceManager.GetString("Miercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X.
        /// </summary>
        public static string MiercolesCorto {
            get {
                return ResourceManager.GetString("MiercolesCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XX:XX.
        /// </summary>
        public static string ModeloHora {
            get {
                return ResourceManager.GetString("ModeloHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar servicio.
        /// </summary>
        public static string ModServicio {
            get {
                return ResourceManager.GetString("ModServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar servicios.
        /// </summary>
        public static string ModServicios {
            get {
                return ResourceManager.GetString("ModServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar trabajo.
        /// </summary>
        public static string ModTrabajo {
            get {
                return ResourceManager.GetString("ModTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar usuario.
        /// </summary>
        public static string ModUsuario {
            get {
                return ResourceManager.GetString("ModUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar informacion.
        /// </summary>
        public static string MostrarInfo {
            get {
                return ResourceManager.GetString("MostrarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo guardado con exito.
        /// </summary>
        public static string MsgAssignmentInsertado {
            get {
                return ResourceManager.GetString("MsgAssignmentInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo modificado con exito.
        /// </summary>
        public static string MsgAssignmentModificado {
            get {
                return ResourceManager.GetString("MsgAssignmentModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea borrar el usuario seleccionado?.
        /// </summary>
        public static string MsgBorrarUsuario {
            get {
                return ResourceManager.GetString("MsgBorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se realiza ningun cambio.
        /// </summary>
        public static string MsgCambiosCancelados {
            get {
                return ResourceManager.GetString("MsgCambiosCancelados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un dia.
        /// </summary>
        public static string MsgDiasService {
            get {
                return ResourceManager.GetString("MsgDiasService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor elija una fecha.
        /// </summary>
        public static string MsgElegirFecha {
            get {
                return ResourceManager.GetString("MsgElegirFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha elegida tiene que ser posterior a este momento.
        /// </summary>
        public static string MsgElegirFechaMayor {
            get {
                return ResourceManager.GetString("MsgElegirFechaMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor elija un turno.
        /// </summary>
        public static string MsgElegirTurnoService {
            get {
                return ResourceManager.GetString("MsgElegirTurnoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor escriba un mensaje para enviarlo.
        /// </summary>
        public static string MsgEscribaMensaje {
            get {
                return ResourceManager.GetString("MsgEscribaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un apellido.
        /// </summary>
        public static string MsgEscribirApellido {
            get {
                return ResourceManager.GetString("MsgEscribirApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca una descripcion.
        /// </summary>
        public static string MsgEscribirDescripcion {
            get {
                return ResourceManager.GetString("MsgEscribirDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un email valido.
        /// </summary>
        public static string MsgEscribirEmail {
            get {
                return ResourceManager.GetString("MsgEscribirEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un nombre.
        /// </summary>
        public static string MsgEscribirNombre {
            get {
                return ResourceManager.GetString("MsgEscribirNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un precio.
        /// </summary>
        public static string MsgEscribirPrecio {
            get {
                return ResourceManager.GetString("MsgEscribirPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un numero de telefono.
        /// </summary>
        public static string MsgEscribirTelefono {
            get {
                return ResourceManager.GetString("MsgEscribirTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca un numero de telefono valido.
        /// </summary>
        public static string MsgEscribirTelefonoValido {
            get {
                return ResourceManager.GetString("MsgEscribirTelefonoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca las horas en los formatos correctos (XX:XX).
        /// </summary>
        public static string MsgHorasMal {
            get {
                return ResourceManager.GetString("MsgHorasMal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para modificar un servicio, hagalo desde la pestaña servicios en la ventana principal..
        /// </summary>
        public static string MsgModificarServiciosPrincipal {
            get {
                return ResourceManager.GetString("MsgModificarServiciosPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario seleccionado no tiene telegram, perdon por las molestias..
        /// </summary>
        public static string MsgNoTelegram {
            get {
                return ResourceManager.GetString("MsgNoTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene Telegram conectado, por lo que algunas funciones esan limitadas.
        ///Puede conectar Telegram en la pestaña Ajustes.
        /// </summary>
        public static string MsgNoTelegramConectado {
            get {
                return ResourceManager.GetString("MsgNoTelegramConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduzca el precio en un formato valido XX,xx.
        /// </summary>
        public static string MsgPrecioMal {
            get {
                return ResourceManager.GetString("MsgPrecioMal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea aplicar todos los cambios realizados?.
        /// </summary>
        public static string MsgRealizarCambiosPregunta {
            get {
                return ResourceManager.GetString("MsgRealizarCambiosPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si borra el servicio, se eliminara automaticamente de todos los usuarios que esten suscritos.
        ///¿Esta seguro de querer eliminarlo?.
        /// </summary>
        public static string MsgSeguroBorrarServicio {
            get {
                return ResourceManager.GetString("MsgSeguroBorrarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea eliminar este trabajo?.
        /// </summary>
        public static string MsgSeguroBorrarTrabajo {
            get {
                return ResourceManager.GetString("MsgSeguroBorrarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea marcar esta(s) deuda(s) como pagada(s)?.
        /// </summary>
        public static string MsgSeguroDeuda {
            get {
                return ResourceManager.GetString("MsgSeguroDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea enviar esta(s) factura(s)?.
        /// </summary>
        public static string MsgSeguroEnviar {
            get {
                return ResourceManager.GetString("MsgSeguroEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea marcar esta(s) factura(s) como pagada(s)?.
        /// </summary>
        public static string MsgSeguroPagar {
            get {
                return ResourceManager.GetString("MsgSeguroPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea marcar esto(s) trabajo(s) como pagado(s)?.
        /// </summary>
        public static string MsgSeguroPagarTrabajo {
            get {
                return ResourceManager.GetString("MsgSeguroPagarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una factura antes.
        /// </summary>
        public static string MsgSeleccionarInvoice {
            get {
                return ResourceManager.GetString("MsgSeleccionarInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione algun item primero.
        /// </summary>
        public static string MsgSeleccionarItem {
            get {
                return ResourceManager.GetString("MsgSeleccionarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un servicio primero.
        /// </summary>
        public static string MsgSeleccionarServicio {
            get {
                return ResourceManager.GetString("MsgSeleccionarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un trabajo primero.
        /// </summary>
        public static string MsgSeleccionarTrabajo {
            get {
                return ResourceManager.GetString("MsgSeleccionarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un turno primero.
        /// </summary>
        public static string MsgSeleccionarTurn {
            get {
                return ResourceManager.GetString("MsgSeleccionarTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un usuario primero.
        /// </summary>
        public static string MsgSeleccionarUsuario {
            get {
                return ResourceManager.GetString("MsgSeleccionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo solo acepta numeros y el separador ,.
        /// </summary>
        public static string MsgSoloNumerosPrecio {
            get {
                return ResourceManager.GetString("MsgSoloNumerosPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En este campo solo se adminten numeros.
        /// </summary>
        public static string MsgSoloNumerosTelegram {
            get {
                return ResourceManager.GetString("MsgSoloNumerosTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo solo acepta numeros y el separador :.
        /// </summary>
        public static string MsgSoloNumerosTurn {
            get {
                return ResourceManager.GetString("MsgSoloNumerosTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea subscribir al usuario en algun servicio?.
        /// </summary>
        public static string MsgSusbscribirUsuarioServicio {
            get {
                return ResourceManager.GetString("MsgSusbscribirUsuarioServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder utilizar las funciones de telegram, primero debe conectarlo en la pestaña &quot;Ajustes&quot;..
        /// </summary>
        public static string MsgTelegramAntes {
            get {
                return ResourceManager.GetString("MsgTelegramAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telegram conectado con exito.
        /// </summary>
        public static string MsgTelegramConectado {
            get {
                return ResourceManager.GetString("MsgTelegramConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar Telegram.
        /// </summary>
        public static string MsgTelegramNoConectado {
            get {
                return ResourceManager.GetString("MsgTelegramNoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno ha sido borrado con exito.
        /// </summary>
        public static string MsgTurnoBorrado {
            get {
                return ResourceManager.GetString("MsgTurnoBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un turno con esas horas.
        /// </summary>
        public static string MsgTurnoExiste {
            get {
                return ResourceManager.GetString("MsgTurnoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: .
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo servicio.
        /// </summary>
        public static string NuevoServicio {
            get {
                return ResourceManager.GetString("NuevoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo trabajo.
        /// </summary>
        public static string NuevoTrabajo {
            get {
                return ResourceManager.GetString("NuevoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear turno nuevo:.
        /// </summary>
        public static string NuevoTurno {
            get {
                return ResourceManager.GetString("NuevoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo usuario.
        /// </summary>
        public static string NuevoUsuario {
            get {
                return ResourceManager.GetString("NuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de telefono.
        /// </summary>
        public static string NumTel {
            get {
                return ResourceManager.GetString("NumTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        public static string Pagar {
            get {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar deuda.
        /// </summary>
        public static string PagarDeuda {
            get {
                return ResourceManager.GetString("PagarDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar trabajos.
        /// </summary>
        public static string PagarTrabajo {
            get {
                return ResourceManager.GetString("PagarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio: .
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sabado.
        /// </summary>
        public static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        public static string SabadoCorto {
            get {
                return ResourceManager.GetString("SabadoCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar usuario.
        /// </summary>
        public static string SelUser {
            get {
                return ResourceManager.GetString("SelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio creado con exito.
        /// </summary>
        public static string ServiceCreado {
            get {
                return ResourceManager.GetString("ServiceCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio modificado con exito.
        /// </summary>
        public static string ServiceModificado {
            get {
                return ResourceManager.GetString("ServiceModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio: .
        /// </summary>
        public static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string Servicios {
            get {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string ServicioSolo {
            get {
                return ResourceManager.GetString("ServicioSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Subscripcion?.
        /// </summary>
        public static string Subscripcion {
            get {
                return ResourceManager.GetString("Subscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono: .
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telegram: .
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno de los servicios a los que esta suscrito ha sido modificado, a continuacion se muestran los nuevos datos:.
        /// </summary>
        public static string TelegramServicioModificado {
            get {
                return ResourceManager.GetString("TelegramServicioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El administrador del sistema ha modificado sus servicios, a continuacion se muestran los servicios a los que esta suscrito ahora mismo:.
        /// </summary>
        public static string TelegramServiciosModificado {
            get {
                return ResourceManager.GetString("TelegramServiciosModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado un nuevo trabajo a su nombre, a continuacion se muestran los datos del mismo: .
        /// </summary>
        public static string TelegramTrabajoCreado {
            get {
                return ResourceManager.GetString("TelegramTrabajoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para borrar este turno, todos los servicios afectados se cambiaran al turno que elija a continuacion.
        /// </summary>
        public static string TextoBorrarTurn {
            get {
                return ResourceManager.GetString("TextoBorrarTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion de cambios.
        /// </summary>
        public static string TituloCambios {
            get {
                return ResourceManager.GetString("TituloCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos.
        /// </summary>
        public static string Trabajos {
            get {
                return ResourceManager.GetString("Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo.
        /// </summary>
        public static string TrabajoSolo {
            get {
                return ResourceManager.GetString("TrabajoSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos pendientes.
        /// </summary>
        public static string TrabajosPendientes {
            get {
                return ResourceManager.GetString("TrabajosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno: .
        /// </summary>
        public static string Turno {
            get {
                return ResourceManager.GetString("Turno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno borrado con exito.
        /// </summary>
        public static string TurnoBorrado {
            get {
                return ResourceManager.GetString("TurnoBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turnos.
        /// </summary>
        public static string Turnos {
            get {
                return ResourceManager.GetString("Turnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario: .
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario creado con exito.
        /// </summary>
        public static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario modificado con exito..
        /// </summary>
        public static string UsuarioModificado {
            get {
                return ResourceManager.GetString("UsuarioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string VerDetalles {
            get {
                return ResourceManager.GetString("VerDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes.
        /// </summary>
        public static string Viernes {
            get {
                return ResourceManager.GetString("Viernes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V.
        /// </summary>
        public static string ViernesCorto {
            get {
                return ResourceManager.GetString("ViernesCorto", resourceCulture);
            }
        }
    }
}
